### ISSUE TITLE
Running on Kind

### ISSUE THREAD

**Issue by learnitall** [cilium/scaffolding#46]
Experiencing various issues when attempting to run on kind for local testing:

## Tools node label

We don't have to worry about this in GKE, but the tools playbook may apply the `scaffolding/app=tools` label onto a control-plane node, which will prevent tools from being scheduled since they don't have the `node-role.kubernetes.io/master:NoSchedule` toleration. I experienced this when working with a kind cluster today, having to manually create the label and set `apply_tool_label` to false.

## Worker node label

If no nodes in the cluster have the `node-role.kubernetes.io/worker` label, then the same issue may occur where a control-plane node gets accidentally labeled as a worker node.

## Metadata collection in benchmark role

This relates to the `test_platform` variable, set in the following lines in `roles/benchmark/tasks/metadata.yml`:

```yaml
- name: Attempt to determine platform - GKE
  shell: |
    export KUBECONFIG={{kubeconfig}}
    kubectl get nodes $(kubectl get nodes -o custom-columns=:.metadata.name --no-headers) -o json | grep "gke.gcr.io"
  register: gke_check
  when: test_platform is undefined

- set_fact:
    test_platform: "gke"
  when: gke_check.rc == 0
```

If `test_platform` is undefined and the platform is not GKE, `Attempt to determine platform - GKE` will fail causing the playbook to fail as well, since we do not have an ignore included. If `test_platform` is defined and the platform is not GKE, then ansible will complain about `gke_check` not being set in the call to `set_fact`. Changing the `when` to `test_platform is undefined and gke_check.rc == 0`, got me though, but adding in an ignore statement might be useful as well.
